version: "3"

services:
  api:
    container_name: api
    restart: always
    build: .
    ports: 
      - "3001:3001"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb: 
    image: mongo:3.5
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"